//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public int Id { get; set; }
        public int QuizBlockId { get; set; }
        public Nullable<int> QuizVariantId { get; set; }
        public byte QuestionScore { get; set; }
        public Nullable<short> QuestionOrder { get; set; }
        public int QuestionId { get; set; }
    
        public virtual QuizBlock QuizBlock { get; set; }
        public virtual Question Question { get; set; }
        public virtual QuizVariant QuizVariant { get; set; }
    }
}
