//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizPassScore
    {
        public int Id { get; set; }
        public short PassScore { get; set; }
        public int EvaluatedBy { get; set; }
        public System.DateTime EvaluatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
